Update package_version_checker.yml

diff --git a/.github/workflows/package_version_checker.yml b/.github/workflows/package_version_checker.yml
--- a/.github/workflows/package_version_checker.yml
+++ b/.github/workflows/package_version_checker.yml
@@ -19,14 +19,12 @@ jobs:
           if [[ ${{ github.event_name }} == 'pull_request' ]]; then
             git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
             diff=$(git diff --name-only HEAD ${{ github.event.pull_request.base.ref }} -- package.json)
-            if [[ -z "$diff" ]]; then
-              echo "::error::Package.json is the same in both branches. Please update the package version."
-              exit 1
-            fi
-
+            
             jsFiles=$(git diff --name-only HEAD ${{ github.event.pull_request.base.ref }} -- '*.js')
-            if [[ -z "$jsFiles" ]]; then
-              echo "::error::No JavaScript files found. Please include JavaScript files in your changes."
-              exit 1
+              if [[ -z "$jsFiles" ]]; then
+                if [[ -z "$diff" ]]; then
+                echo "::error::Package.json is the same in both branches. Please update the package version."
+                exit 1
+              fi
             fi
           fi
